version: '2'
services:
    jhipster_oracle_limits_and_skipclient-app:
        image: jhipster_oracle_limits_and_skipclient
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jhipster_oracle_limits_and_skipclient-oracle:1521:jhipster_oracle_limits_and_skipclient
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
